### ISSUE TITLE
Model weight link is not accessible anymore

### ISSUE THREAD

**Issue by Nattagit4711** [stanfordmlgroup/VisualCheXbert#2]
Model weight link provided is not accessible anymore.  Could you pls provide the new one?
(https://drive.google.com/file/d/1Od62LAbdmfcK6W8TfzNcLIUouxWZoMHn/view?usp=sharing) 
@saahil9jain

**Comment by Suyash-A** [comment]
I am also facing this issue.

**Comment by saahil9jain** [comment]
Hey!! Thanks for bringing this up! I've updated the link so that it's accessible on the README.

Link: https://drive.google.com/file/d/1QmwAurEmiXc-_uF0JrgAbWCxpF-pl52s/view?usp=drive_link

Let me know if there's any issues - appreciate you pointing this out.
